[tool.poetry]
name = "peer_oracle_vcn"
version = "0.2.0"
description = ""
authors = ["Byeonghoon Yoo <bh322yoo@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
oci = "^2.44.2"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
flake8 = "^3.9.2"
python-dotenv = "^0.19.0"
pytest = "^6.2.5"

[tool.poetry.scripts]
peer_oracle_vcn = 'peer_oracle_vcn:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
skip-string-normalization = true